/*
 * Decompiled with CFR 0.150.
 */
import a.a;

public class iReSqtkUVgSzRiReSqtkUVg {
    public static final Class a = a.a.gc("net/minecraftforge/common/ForgeVersion");
    public static final Class b = a.a.gc("net/minecraft/client/Minecraft");
    public static final Class c = a.a.gc("net/minecraft/entity/Entity");
    public static final Class d = a.a.gc("net/minecraft/entity/player/EntityPlayer");
    public static final Class e = a.a.gc("net/minecraft/client/entity/EntityPlayerSP");
    public static final Class f = a.a.gc("net/minecraft/client/gui/GuiScreen");
    public static final Class g = a.a.gc("net/minecraft/client/gui/GuiChat");
    public static final Class h = a.a.gc("net/minecraft/util/Session");
    public static final Class i = a.a.gc("net/minecraft/client/settings/GameSettings");
    public static final Class j = a.a.gc("net/minecraft/client/settings/KeyBinding");
    public static final Class k = a.a.gc("net/minecraft/world/World");
    public static final Class l = a.a.gc("net/minecraft/world/WorldProvider");
    public static final Class m = a.a.gc("net/minecraft/client/multiplayer/WorldClient");
    public static final Class n = a.a.gc("net/minecraft/entity/EntityLivingBase");
    public static final Class o = a.a.gc("net/minecraft/client/gui/FontRenderer");
    public static final Class p = a.a.gc("net/minecraft/util/MovementInput");
    public static final Class q = a.a.gc("net/minecraft/client/multiplayer/PlayerControllerMP");
    public static final Class r = a.a.gc("net/minecraft/client/renderer/EntityRenderer");
    public static final Class s = a.a.gc("net/minecraft/entity/item/EntityItemFrame");
    public static final Class t = a.a.gc("net/minecraft/client/gui/ScaledResolution");
    public static final Class u = a.a.gc("net/minecraft/entity/player/InventoryPlayer");
    public static final Class v = a.a.gc("net/minecraft/item/ItemStack");
    public static final Class w = a.a.gc("net/minecraft/item/Item");
    public static final Class x = a.a.gc("net/minecraft/item/ItemPotion");
    public static final Class y = a.a.gc("net/minecraft/client/gui/inventory/GuiContainer");
    public static final Class z = a.a.gc("net/minecraft/inventory/Slot");
    public static final Class A = a.a.gc("net/minecraft/inventory/Container");
    public static final Class B = a.a.gc("net/minecraft/client/entity/EntityOtherPlayerMP");
    public static final Class C = a.a.gc("net/minecraft/client/renderer/entity/RenderManager");
    public static final Class D = a.a.gc("net/minecraft/entity/monster/EntityMob");
    public static final Class E = a.a.gc("net/minecraft/entity/passive/EntityAnimal");
    public static final Class F = a.a.gc("net/minecraft/entity/monster/EntitySlime");
    public static final Class G = a.a.gc("net/minecraft/block/Block");
    public static final Class H = a.a.gc("net/minecraft/item/ItemEnderPearl");
    public static final Class I = a.a.gc("net/minecraft/item/ItemFood");
    public static final Class J = a.a.gc("net/minecraft/item/ItemSword");
    public static final Class K = a.a.gc("net/minecraft/client/renderer/Tessellator");
    public static final Class L;
    public static final Class M;
    public static final Class N;
    public static final Class O;
    public static final Class P;
    public static final Class Q;
    public static final Class R;
    public static final Class S;
    public static final Class T;
    public static final Class U;
    public static final Class V;
    public static final Class W;
    public static final Class X;
    public static final Class Y;
    public static final Class Z;
    public static final Class aa;
    public static final Class ab;
    public static final Class ac;
    public static final Class ad;
    public static final Class ae;
    public static final Class af;
    public static final Class ag;
    public static final Class ah;
    public static final Class ai;
    public static final Class aj;
    public static final Class ak;
    public static final Class al;
    public static final Class am;
    public static final Class an;
    public static final Class ao;
    public static final Class ap;
    public static final Class aq;
    public static final Class ar;
    public static final Class as;
    public static final Class at;
    public static final Class au;
    public static final Class av;
    public static final Class aw;
    public static final Class ax;
    public static final Class ay;
    public static final Class az;
    public static final Class aA;
    public static final Class aB;
    public static final Class aC;
    public static final Class aD;
    public static final Class aE;
    public static final Class aF;
    public static final Class aG;
    public static final Class aH;
    public static final Class aI;
    public static final Class aJ;
    public static final Class aK;
    public static final Class aL;
    public static final Class aM;
    public static final Class aN;
    public static final Class aO;
    public static final Class aP;
    public static final Class aQ;
    public static final Class aR;
    public static final Class aS;
    public static final Class aT;
    public static final Class aU;
    public static final Class aV;
    public static final Class aW;
    public static final Class aX;
    public static final Class aY;
    public static final Class aZ;
    public static final Class ba;
    public static final Class bb;
    public static final Class bc;
    public static final Class bd;
    public static final Class be;
    public static final Class bf;
    public static final Class bg;
    public static final Class bh;
    public static final Class bi;
    public static final Class bj;
    public static final Class bk;
    public static final Class bl;
    public static final Class bm;
    public static final Class bn;
    public static final Class bo;
    public static final Class bp;
    public static final Class bq;
    public static final Class br;
    public static final Class bs;
    public static final Class bt;
    public static final Class bu;
    public static final Class bv;
    public static final Class bw;
    public static final Class bx;
    public static final Class by;
    public static final Class bz;
    public static final Class bA;
    public static final Class bB;
    public static final Class bC;
    public static final Class bD;
    public static final Class bE;
    public static final Class bF;
    public static final Class bG;
    public static final Class bH;
    public static final Class bI;
    public static final Class bJ;
    public static final Class bK;
    public static final Class bL;
    public static final Class bM;
    public static final Class bN;
    public static final Class bO;
    public static final Class bP;
    public static final Class bQ;
    public static Class bR;
    public static Class bS;
    public static Class bT;
    public static Class bU;
    public static Class bV;
    public static Class bW;
    public static Class bX;
    public static Class bY;
    public static Class bZ;
    public static Class ca;
    public static Class cb;
    public static Class cc;
    public static Class cd;
    public static Class ce;
    public static Class cf;
    public static Class cg;
    public static Class ch;
    public static Class ci;
    public static Class cj;
    public static Class ck;
    public static Class cl;
    public static Class cm;
    public static Class cn;
    public static Class co;
    public static Class cp;
    public static Class cq;
    public static Class cr;
    public static Class cs;
    public static Class ct;
    public static Class cu;
    public static Class cv;
    public static Class cw;
    public static Class cx;
    public static Class cy;
    public static Class cz;
    public static Class cA;
    public static Class cB;
    public static Class cC;
    public static Class cD;
    public static Class cE;
    public static Class cF;
    public static Class cG;
    public static Class cH;
    public static Class cI;
    public static Class cJ;
    public static Class cK;
    public static Class cL;
    public static Class cM;
    public static Class cN;
    public static Class cO;
    public static Class cP;
    public static Class cQ;
    public static Class cR;
    public static Class cS;
    public static Class cT;
    public static Class cU;
    public static Class cV;
    public static Class cW;
    public static String cX;
    public static String cY;

    static {
        N = a.a.gc("net/minecraftforge/client/event/MouseEvent");
        O = a.a.gc("net/minecraftforge/common/MinecraftForge");
        P = a.a.gc("net/minecraft/client/renderer/texture/TextureManager");
        Q = a.a.gc("net/minecraft/client/resources/IResourceManager");
        R = a.a.gc("net/minecraft/client/shader/Framebuffer");
        S = a.a.gc("net/minecraft/util/ResourceLocation");
        T = a.a.gc("net/minecraft/client/shader/ShaderGroup");
        U = a.a.gc("net/minecraft/init/Blocks");
        V = a.a.gc("net/minecraft/block/material/Material");
        W = a.a.gc("net/minecraft/block/BlockFence");
        X = a.a.gc("net/minecraft/block/BlockWall");
        Y = a.a.gc("net/minecraft/block/BlockFenceGate");
        Z = a.a.gc("net/minecraft/block/BlockChest");
        aa = a.a.gc("net/minecraft/client/network/NetHandlerPlayClient");
        ab = a.a.gc("net/minecraft/network/Packet");
        ac = a.a.gc("net/minecraft/potion/Potion");
        ad = a.a.gc("net/minecraft/potion/PotionEffect");
        ae = a.a.gc("net/minecraft/entity/passive/EntityAmbientCreature");
        af = a.a.gc("net/minecraft/network/NetworkManager");
        ag = a.a.gc("io/netty/channel/Channel");
        ah = a.a.gc("net/minecraft/network/INetHandler");
        ai = a.a.gc("io/netty/util/concurrent/GenericFutureListener");
        aj = a.a.gc("net/minecraft/network/NetworkManager$InboundHandlerTuplePacketListener");
        ak = a.a.gc("net/minecraft/client/gui/inventory/GuiChest");
        al = a.a.gc("net/minecraft/inventory/IInventory");
        am = a.a.gc("net/minecraft/util/Timer");
        an = a.a.gc("net/minecraft/util/FoodStats");
        ao = a.a.gc("net/minecraft/entity/ai/attributes/IAttributeInstance");
        ap = a.a.gc("net/minecraft/entity/ai/attributes/AttributeModifier");
        aq = a.a.gc("net/minecraft/entity/ai/attributes/IAttribute");
        ar = a.a.gc("net/minecraft/entity/SharedMonsterAttributes");
        as = a.a.gc("net/minecraft/item/ItemAxe");
        at = a.a.gc("net/minecraft/entity/EntityCreature");
        au = a.a.gc("net/minecraft/scoreboard/Team");
        av = a.a.gc("net/minecraft/client/settings/GameSettings$Options");
        aw = a.a.gc("net/minecraft/client/renderer/RenderGlobal");
        ax = a.a.gc("net/minecraft/item/ItemBlock");
        ay = a.a.gc("com/mojang/authlib/GameProfile");
        az = a.a.gc("net/minecraft/item/ItemSnowball");
        aA = a.a.gc("net/minecraft/item/ItemEgg");
        aB = a.a.gc("net/minecraft/tileentity/TileEntity");
        aC = a.a.gc("net/minecraft/tileentity/TileEntityChest");
        aD = a.a.gc("net/minecraft/tileentity/TileEntityEnderChest");
        aE = a.a.gc("net/minecraft/tileentity/TileEntityMobSpawner");
        aF = a.a.gc("net/minecraft/tileentity/TileEntityHopper");
        aG = a.a.gc("net/minecraft/tileentity/TileEntityFurnace");
        aH = a.a.gc("net/minecraft/tileentity/TileEntityDropper");
        aI = a.a.gc("net/minecraft/tileentity/TileEntityDispenser");
        aJ = a.a.gc("net/minecraft/tileentity/MobSpawnerBaseLogic");
        aK = a.a.gc("net/minecraftforge/client/IRenderHandler");
        aL = a.a.gc("net/minecraftforge/client/event/RenderBlockOverlayEvent");
        aM = a.a.gc("net/minecraft/item/ItemSoup");
        aN = a.a.gc("net/minecraft/entity/player/PlayerCapabilities");
        aO = a.a.gc("net/minecraft/item/ItemArmor");
        aP = a.a.gc("net/minecraft/enchantment/EnchantmentHelper");
        aQ = a.a.gc("net/minecraft/enchantment/Enchantment");
        aR = a.a.gc("net/minecraft/nbt/NBTTagList");
        aS = a.a.gc("net/minecraft/nbt/NBTTagCompound");
        aT = a.a.gc("net/minecraft/client/model/ModelRenderer");
        aU = a.a.gc("net/minecraft/entity/EnumCreatureAttribute");
        aV = a.a.gc("net/minecraft/util/DamageSource");
        aW = a.a.gc("net/minecraft/item/ItemBow");
        aX = a.a.gc("net/minecraft/item/ItemTool");
        aY = a.a.gc("net/minecraft/item/ItemFishingRod");
        aZ = a.a.gc("net/minecraft/item/ItemGlassBottle");
        ba = a.a.gc("net/minecraft/item/ItemBucket");
        bb = a.a.gc("net/minecraft/item/ItemAppleGold");
        bc = a.a.gc("net/minecraft/item/ItemPickaxe");
        bd = a.a.gc("net/minecraft/item/ItemSpade");
        be = a.a.gc("net/minecraft/init/Items");
        bf = a.a.gc("net/minecraft/client/renderer/RenderHelper");
        bg = a.a.gc("net/minecraft/network/play/INetHandlerPlayClient");
        bh = a.a.gc("net/minecraft/util/MouseHelper");
        bi = a.a.gc("net/minecraft/world/chunk/Chunk");
        bj = a.a.gc("net/minecraft/world/chunk/IChunkProvider");
        bk = a.a.gc("net/minecraft/client/renderer/texture/ITextureObject");
        bl = a.a.gc("net/minecraft/block/BlockLiquid");
        bm = a.a.gc("net/minecraft/client/gui/inventory/GuiInventory");
        bn = a.a.gc("net/minecraft/client/renderer/entity/Render");
        bo = a.a.gc("net/minecraft/client/model/ModelBase");
        bp = a.a.gc("net/minecraft/client/model/ModelBiped");
        bq = a.a.gc("net/minecraft/client/renderer/entity/RenderPlayer");
        br = a.a.gc("net/minecraft/entity/projectile/EntityPotion");
        bs = a.a.gc("net/minecraft/entity/projectile/EntityFishHook");
        bt = a.a.gc("net/minecraft/entity/projectile/EntityArrow");
        bu = a.a.gc("net/minecraft/entity/projectile/EntityThrowable");
        bv = a.a.gc("net/minecraft/entity/IProjectile");
        bw = a.a.gc("net/minecraft/entity/monster/EntityEnderman");
        bx = a.a.gc("net/minecraft/entity/projectile/EntitySnowball");
        by = a.a.gc("net/minecraft/entity/item/EntityEnderPearl");
        bz = a.a.gc("net/minecraft/entity/projectile/EntityEgg");
        bA = a.a.gc("net/minecraftforge/client/event/GuiScreenEvent");
        bB = a.a.gc("net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent");
        bC = a.a.gc("net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Pre");
        bD = a.a.gc("net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post");
        bE = a.a.gc("net/minecraft/launchwrapper/LaunchClassLoader");
        bF = a.a.gc("net/minecraft/launchwrapper/Launch");
        bG = a.a.gc("io/netty/channel/ChannelHandlerContext");
        bH = a.a.gc("net/minecraftforge/client/event/ClientChatReceivedEvent");
        bI = a.a.gc("net/minecraft/item/Item$ToolMaterial");
        bJ = a.a.gc("net/minecraft/item/ItemArmor$ArmorMaterial");
        bK = a.a.gc("net/minecraftforge/client/event/RenderLivingEvent");
        bU = a.a.gc("net/minecraft/util/EnumFacing");
        if (iReSqtkUVgauSiReSqtkUVg.d() > 13) {
            if (iReSqtkUVgauSiReSqtkUVg.d() >= 23) {
                bS = a.a.gc("net/minecraft/util/math/Vec3i");
                bT = a.a.gc("net/minecraft/util/math/BlockPos");
                bV = a.a.gc("net/minecraft/block/state/IBlockState");
                bW = a.a.gc("net/minecraft/network/play/client/CPacketEntityAction$Action");
            } else {
                bS = a.a.gc("net/minecraft/util/Vec3i");
                bT = a.a.gc("net/minecraft/util/BlockPos");
                bV = a.a.gc("net/minecraft/block/state/IBlockState");
                bW = a.a.gc("net/minecraft/network/play/client/C0BPacketEntityAction$Action");
            }
            bY = a.a.gc("net/minecraft/client/network/NetworkPlayerInfo");
            L = a.a.gc("net/minecraftforge/fml/common/eventhandler/Event");
            M = a.a.gc("net/minecraftforge/fml/common/eventhandler/EventBus");
            bL = a.a.gc("net/minecraftforge/fml/common/gameevent/TickEvent");
            bN = a.a.gc("net/minecraftforge/fml/common/gameevent/TickEvent$Phase");
            bM = a.a.gc("net/minecraftforge/fml/common/gameevent/TickEvent$RenderTickEvent");
            bO = a.a.gc("net/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent");
            bP = a.a.gc("net/minecraftforge/fml/common/gameevent/InputEvent$KeyInputEvent");
            bX = a.a.gc("net/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent");
            cX = "net/minecraftforge/";
            bZ = a.a.gc("net/minecraft/entity/item/EntityArmorStand");
            ca = a.a.gc("net/minecraft/client/renderer/vertex/VertexFormat");
            cb = a.a.gc("net/minecraft/client/renderer/vertex/DefaultVertexFormats");
            cd = a.a.gc("net/minecraft/client/model/ModelPlayer");
            cR = a.a.gc("net/minecraft/world/IBlockAccess");
        } else {
            cc = a.a.gc("net/minecraft/command/IEntitySelector");
            L = a.a.gc("cpw/mods/fml/common/eventhandler/Event");
            M = a.a.gc("cpw/mods/fml/common/eventhandler/EventBus");
            bL = a.a.gc("cpw/mods/fml/common/gameevent/TickEvent");
            bN = a.a.gc("cpw/mods/fml/common/gameevent/TickEvent$Phase");
            bO = a.a.gc("cpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent");
            bM = a.a.gc("cpw/mods/fml/common/gameevent/TickEvent$RenderTickEvent");
            bP = a.a.gc("cpw/mods/fml/common/gameevent/InputEvent$KeyInputEvent");
            bX = a.a.gc("cpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent");
            bR = a.a.gc("net/minecraft/client/entity/EntityClientPlayerMP");
            cX = "cpw/mods/";
        }
        if (iReSqtkUVgauSiReSqtkUVg.d() >= 23) {
            ce = a.a.gc("net/minecraft/util/math/Vec3d");
            cf = a.a.gc("net/minecraft/util/math/AxisAlignedBB");
            cg = a.a.gc("net/minecraft/util/math/RayTraceResult");
            ch = a.a.gc("net/minecraft/util/math/RayTraceResult$Type");
            ci = a.a.gc("net/minecraft/network/play/client/CPacketKeepAlive");
            cj = a.a.gc("net/minecraft/network/play/client/CPacketAnimation");
            ck = a.a.gc("net/minecraft/network/play/client/CPacketEntityAction");
            cl = a.a.gc("net/minecraft/network/play/client/CPacketChatMessage");
            cm = a.a.gc("net/minecraft/network/play/client/CPacketUseEntity");
            cn = a.a.gc("net/minecraft/network/play/client/CPacketPlayer");
            co = a.a.gc("net/minecraft/network/play/client/CPacketPlayerDigging");
            cp = a.a.gc("net/minecraft/network/play/client/CPacketHeldItemChange");
            cq = a.a.gc("net/minecraft/client/renderer/RenderItem");
            cr = a.a.gc("net/minecraft/network/play/client/CPacketUseEntity$Action");
            cs = a.a.gc("net/minecraft/entity/ai/attributes/AbstractAttributeMap");
            ct = a.a.gc("net/minecraft/util/text/ITextComponent");
            cu = a.a.gc("net/minecraft/util/text/TextComponentString");
            cv = a.a.gc("net/minecraft/util/text/Style");
            cw = a.a.gc("net/minecraft/util/text/TextComponentTranslation");
            cx = a.a.gc("net/minecraft/client/renderer/BufferBuilder");
            cy = a.a.gc("net/minecraft/network/play/server/SPacketExplosion");
            cz = a.a.gc("net/minecraft/network/play/server/SPacketEntityVelocity");
            cA = a.a.gc("net/minecraft/network/play/server/SPacketEntity");
            cB = a.a.gc("net/minecraft/network/play/server/SPacketEntityTeleport");
            cC = a.a.gc("net/minecraft/network/play/server/SPacketPlayerPosLook");
            cD = a.a.gc("net/minecraft/client/renderer/entity/RenderLivingBase");
            cE = a.a.gc("net/minecraft/util/registry/RegistryNamespaced");
            cF = a.a.gc("net/minecraft/util/registry/RegistrySimple");
            cH = a.a.gc("net/minecraft/network/play/client/CPacketPlayer$Rotation");
            cI = a.a.gc("net/minecraft/network/play/client/CPacketPlayer$Position");
            cJ = a.a.gc("net/minecraft/network/play/client/CPacketPlayer$PositionRotation");
            cT = a.a.gc("net/minecraft/entity/MoverType");
            cK = a.a.gc("net/minecraft/util/SoundEvent");
            cL = a.a.gc("net/minecraft/util/EnumHand");
            cM = a.a.gc("net/minecraft/inventory/ClickType");
            cN = a.a.gc("net/minecraft/util/EnumActionResult");
            cO = a.a.gc("net/minecraft/util/NonNullList");
            cP = a.a.gc("net/minecraft/inventory/EntityEquipmentSlot");
            cQ = a.a.gc("net/minecraft/potion/PotionUtils");
            cS = a.a.gc("net/minecraft/item/ItemSplashPotion");
        } else {
            ce = a.a.gc("net/minecraft/util/Vec3");
            cf = a.a.gc("net/minecraft/util/AxisAlignedBB");
            cg = a.a.gc("net/minecraft/util/MovingObjectPosition");
            ch = a.a.gc("net/minecraft/util/MovingObjectPosition$MovingObjectType");
            ci = a.a.gc("net/minecraft/network/play/client/C00PacketKeepAlive");
            cj = a.a.gc("net/minecraft/network/play/client/C0APacketAnimation");
            ck = a.a.gc("net/minecraft/network/play/client/C0BPacketEntityAction");
            cl = a.a.gc("net/minecraft/network/play/client/C01PacketChatMessage");
            cm = a.a.gc("net/minecraft/network/play/client/C02PacketUseEntity");
            cn = a.a.gc("net/minecraft/network/play/client/C03PacketPlayer");
            co = a.a.gc("net/minecraft/network/play/client/C07PacketPlayerDigging");
            cp = a.a.gc("net/minecraft/network/play/client/C09PacketHeldItemChange");
            cq = a.a.gc("net/minecraft/client/renderer/entity/RenderItem");
            cr = a.a.gc("net/minecraft/network/play/client/C02PacketUseEntity$Action");
            cs = a.a.gc("net/minecraft/entity/ai/attributes/BaseAttributeMap");
            ct = a.a.gc("net/minecraft/util/IChatComponent");
            cu = a.a.gc("net/minecraft/util/ChatComponentText");
            cv = a.a.gc("net/minecraft/util/ChatComponentStyle");
            cw = a.a.gc("net/minecraft/util/ChatComponentTranslation");
            cx = a.a.gc("net/minecraft/client/renderer/WorldRenderer");
            cy = a.a.gc("net/minecraft/network/play/server/S27PacketExplosion");
            cz = a.a.gc("net/minecraft/network/play/server/S12PacketEntityVelocity");
            cA = a.a.gc("net/minecraft/network/play/server/S14PacketEntity");
            cB = a.a.gc("net/minecraft/network/play/server/S18PacketEntityTeleport");
            cC = a.a.gc("net/minecraft/network/play/server/S08PacketPlayerPosLook");
            cD = a.a.gc("net/minecraft/client/renderer/entity/RendererLivingEntity");
            cE = a.a.gc("net/minecraft/util/RegistryNamespaced");
            cF = a.a.gc("net/minecraft/util/RegistrySimple");
            cG = a.a.gc("net/minecraftforge/event/entity/player/PlayerInteractEvent$Action");
            cH = a.a.gc("net/minecraft/network/play/client/C03PacketPlayer$C05PacketPlayerLook");
            cI = a.a.gc("net/minecraft/network/play/client/C03PacketPlayer$C04PacketPlayerPosition");
            cJ = a.a.gc("net/minecraft/network/play/client/C03PacketPlayer$C06PacketPlayerPosLook");
            cU = a.a.gc("net/minecraft/client/particle/EffectRenderer");
            cV = a.a.gc("net/minecraft/client/particle/EntityCritFX");
            cW = a.a.gc("net/minecraft/client/particle/EntityCrit2FX");
        }
        bQ = a.a.gc("net/minecraftforge/client/event/RenderHandEvent");
        cY = cX.replace("/", ".");
    }
}

