/*
 * Decompiled with CFR 0.150.
 */
package manthe;

import java.util.ArrayList;
import java.util.List;
import javassist.bytecode.CodeAttribute$RuntimeCopyException;
import manthe.A5;
import manthe.V;
import manthe.cy;
import manthe.g6;
import manthe.g8;
import manthe.gB;
import manthe.gE;
import manthe.gF;
import manthe.gJ;
import manthe.gL;
import manthe.gP;
import manthe.gR;
import manthe.gT;
import manthe.gX;
import manthe.gY;
import manthe.gm;
import manthe.gr;
import manthe.gs;
import manthe.gv;
import manthe.h0;
import manthe.h1;
import manthe.h2;
import manthe.h3;
import manthe.h4;
import manthe.h5;
import manthe.h6;
import manthe.h8;
import manthe.h9;
import manthe.hA;
import manthe.hB;
import manthe.hC;
import manthe.hD;
import manthe.hE;
import manthe.hF;
import manthe.hG;
import manthe.hH;
import manthe.hI;
import manthe.hJ;
import manthe.hK;
import manthe.hL;
import manthe.hM;
import manthe.hN;
import manthe.hO;
import manthe.hP;
import manthe.hQ;
import manthe.hR;
import manthe.hS;
import manthe.hT;
import manthe.hU;
import manthe.hV;
import manthe.hW;
import manthe.hX;
import manthe.hY;
import manthe.hZ;
import manthe.h_;
import manthe.ha;
import manthe.hb;
import manthe.hc;
import manthe.hd;
import manthe.he;
import manthe.hf;
import manthe.hg;
import manthe.hh;
import manthe.hi;
import manthe.hj;
import manthe.hk;
import manthe.hl;
import manthe.hm;
import manthe.ho;
import manthe.hp;
import manthe.hq;
import manthe.hr;
import manthe.hs;
import manthe.ht;
import manthe.hu;
import manthe.hv;
import manthe.hw;
import manthe.hx;
import manthe.hy;
import manthe.hz;
import manthe.i0;
import manthe.i1;
import manthe.i2;
import manthe.i3;
import manthe.i4;
import manthe.i5;
import manthe.i6;
import manthe.i7;
import manthe.i8;
import manthe.i9;
import manthe.iA;
import manthe.iB;
import manthe.iE;
import manthe.iF;
import manthe.iG;
import manthe.iH;
import manthe.iI;
import manthe.iJ;
import manthe.iK;
import manthe.iL;
import manthe.iM;
import manthe.iN;
import manthe.iO;
import manthe.iP;
import manthe.iQ;
import manthe.iR;
import manthe.iS;
import manthe.iT;
import manthe.iU;
import manthe.iV;
import manthe.iW;
import manthe.iX;
import manthe.iY;
import manthe.iZ;
import manthe.i_;
import manthe.ia;
import manthe.ib;
import manthe.ic;
import manthe.id;
import manthe.ie;
import manthe.ig;
import manthe.ih;
import manthe.ij;
import manthe.ik;
import manthe.il;
import manthe.im;
import manthe.in;
import manthe.io;
import manthe.ip;
import manthe.ir;
import manthe.is;
import manthe.it;
import manthe.iu;
import manthe.iv;
import manthe.iw;
import manthe.ix;
import manthe.iy;
import manthe.iz;
import manthe.j0;
import manthe.j1;
import manthe.j2;
import manthe.j3;
import manthe.j4;
import manthe.j5;
import manthe.j6;
import manthe.j7;
import manthe.j8;
import manthe.j9;
import manthe.jA;
import manthe.jB;
import manthe.jC;
import manthe.jD;
import manthe.jE;
import manthe.jF;
import manthe.jH;
import manthe.jI;
import manthe.jJ;
import manthe.jK;
import manthe.jL;
import manthe.jM;
import manthe.jO;
import manthe.jP;
import manthe.jQ;
import manthe.jR;
import manthe.jS;
import manthe.jT;
import manthe.jU;
import manthe.jV;
import manthe.jW;
import manthe.jX;
import manthe.jY;
import manthe.jZ;
import manthe.j_;
import manthe.ja;
import manthe.jb;
import manthe.jc;
import manthe.jd;
import manthe.je;
import manthe.jf;
import manthe.jg;
import manthe.jh;
import manthe.jj;
import manthe.jk;
import manthe.jl;
import manthe.jm;
import manthe.jn;
import manthe.jo;
import manthe.jp;
import manthe.jq;
import manthe.jr;
import manthe.js;
import manthe.jt;
import manthe.ju;
import manthe.jv;
import manthe.jw;
import manthe.jx;
import manthe.jy;
import manthe.jz;
import manthe.k3;
import manthe.k7;
import manthe.kI;
import manthe.kM;
import manthe.kQ;
import manthe.kg;
import manthe.kk;
import manthe.ko;
import manthe.on;

public class t {
    public static List<gJ> b_ = new ArrayList<gJ>();
    public h5 bW;
    public hC aA;
    public hA ca;
    public jP g;
    public iz e;
    public iw am;
    public i_ M;
    public ie a0;
    public ix b;
    public iA aF;
    public he aJ;
    public it aL;
    public kI s;
    public hE d;
    public hx bC;
    public hQ U;
    public hk c;
    public ho R;
    public jy Y;
    public hm bA;
    public jD a_;
    public kg V;
    public jj bZ;
    public j0 cu;
    public hb aU;
    public h6 X;
    public h2 bj;
    public jC bN;
    public jT aM;
    public id br;
    public i6 au;
    public iT u;
    public hr bz;
    public hL av;
    public is h;
    public iX b5;
    public gB aa;
    public gm q;
    public gX aY;
    public gE cq;
    public h3 P;
    public iV aQ;
    public io z;
    public hc b0;
    public gP b9;
    public hS bP;
    public hO a;
    public hU bY;
    public g8 bh;
    public g6 a1;
    public gs bG;
    public i1 bq;
    public hP b7;
    public ir an;
    public ht aP;
    public hq aw;
    public j7 cr;
    public jK Z;
    public jw B;
    public jk aX;
    public j9 bR;
    public jb aB;
    public j4 bp;
    public jh bK;
    public jf a4;
    public j1 aT;
    public jl as;
    public jz bT;
    public jH o;
    public jS cp;
    public jU ad;
    public ju bH;
    public hW bb;
    public hh bS;
    public jQ ao;
    public ko co;
    public jo ap;
    public j3 b8;
    public ik cj;
    public hJ i;
    public im aV;
    public jp be;
    public jW m;
    public jV cc;
    public jX ce;
    public ic bx;
    public i5 aI;
    public iu j;
    public iE bO;
    public ig b2;
    public il bf;
    public jq ck;
    public jE aN;
    public hF ae;
    public gr cw;
    public gL bt;
    public je L;
    public iI ag;
    public i7 ak;
    public i9 F;
    public iG bs;
    public jd a5;
    public jc v;
    public hu bd;
    public k7 O;
    public gY bV;
    public ij bk;
    public iy C;
    public in bU;
    public iN cy;
    public iZ bE;
    public jM W;
    public jg H;
    public jt ay;
    public jZ N;
    public j_ ac;
    public gv I;
    public ia a2;
    public jL a3;
    public iL aE;
    public hV ch;
    public iM aG;
    public jn T;
    public ja ai;
    public jI b4;
    public jF S;
    public h9 bB;
    public jJ cz;
    public gR bI;
    public k3 bF;
    public kQ bo;
    public h_ bQ;
    public kM a6;
    public hs aC;
    public h8 cl;
    public hB ah;
    public hR cx;
    public iW bD;
    public ih Q;
    public jY a9;
    public jv w;
    public h4 ax;
    public iJ aS;
    public i2 aH;
    public hl bg;
    public hg x;
    public hI bM;
    public hM K;
    public jB D;
    public jR bu;
    public iU bi;
    public i8 bJ;
    public iB cd;
    public ip ct;
    public hy bm;
    public h0 E;
    public hw n;
    public hz cs;
    public jx ci;
    public jA bn;
    public js bw;
    public jO cm;
    public ib G;
    public i4 aO;
    public gT at;
    public hj bc;
    public j8 bv;
    public iv cn;
    public iY b1;
    public iP aW;
    public iF ab;
    public jr r;
    public j2 az;
    public iR aR;
    public hG cv;
    public hd ba;
    public i0 bX;
    public gF aq;
    public j6 af;
    public iO k;
    public hi a7;
    public kk J;
    public jm bl;
    public hX aZ;
    public iS b6;
    public iK aD;
    public iH p;
    public iQ a8;
    public i3 cf;
    public hT by;
    public hD y;
    public hf A;
    public hK cb;
    public h1 b3;
    public hH cg;
    public hZ bL;
    public ha aj;
    public hN l;
    public j5 f;
    public hp ar;
    public hv al;
    public hY t;
    private static String[] aK;

    public void c() {
        block20: {
            int n6;
            block19: {
                block18: {
                    block17: {
                        block16: {
                            block15: {
                                block14: {
                                    n6 = gJ.b();
                                    if (n6 != 0) {
                                        if (!on.p.h()) {
                                            this.U = new hQ();
                                            this.c = new hk();
                                            this.R = new ho();
                                            this.aU = new hb();
                                            this.q = new gm();
                                            this.aY = new gX();
                                            this.cq = new gE();
                                            this.P = new h3();
                                            this.b9 = new gP();
                                            this.bh = new g8();
                                            this.a1 = new g6();
                                            this.bb = new hW();
                                            this.bS = new hh();
                                            this.bV = new gY();
                                            this.at = new gT();
                                            this.I = new gv();
                                            this.ch = new hV();
                                            this.bB = new h9();
                                            this.bI = new gR();
                                            this.ax = new h4();
                                            this.bg = new hl();
                                            this.bM = new hI();
                                            this.K = new hM();
                                            this.x = new hg();
                                            this.n = new hw();
                                            this.cs = new hz();
                                            this.cv = new hG();
                                            this.bG = new gs();
                                            this.bd = new hu();
                                            this.O = new k7();
                                            t t2 = this;
                                            if (n6 != 0) {
                                                t2.aq = new gF();
                                                if (manthe.V.c() > 13) {
                                                    this.aa = new gB();
                                                }
                                                t2 = this;
                                            }
                                            t2.ct = new ip();
                                        }
                                        this.bW = new h5();
                                        this.aA = new hC();
                                        this.ca = new hA();
                                        this.g = new jP();
                                        this.e = new iz();
                                        this.am = new iw();
                                        this.M = new i_();
                                        this.a0 = new ie();
                                        this.b = new ix();
                                        this.aF = new iA();
                                        this.aJ = new he();
                                        this.aL = new it();
                                        this.s = new kI();
                                        this.d = new hE();
                                        this.bC = new hx();
                                        this.Y = new jy();
                                        this.bA = new hm();
                                        this.a_ = new jD();
                                        this.bZ = new jj();
                                        this.cu = new j0();
                                        this.X = new h6();
                                        this.bj = new h2();
                                        this.aM = new jT();
                                        this.br = new id();
                                        this.au = new i6();
                                        this.u = new iT();
                                        this.bz = new hr();
                                        this.av = new hL();
                                        this.h = new is();
                                        this.b5 = new iX();
                                        this.aQ = new iV();
                                        this.z = new io();
                                        this.cl = new h8();
                                        this.b0 = new hc();
                                        this.bP = new hS();
                                        this.a = new hO();
                                        this.bq = new i1();
                                        this.an = new ir();
                                        this.aP = new ht();
                                        this.cr = new j7();
                                        this.B = new jw();
                                        this.Z = new jK();
                                        this.aX = new jk();
                                        this.bK = new jh();
                                        this.bp = new j4();
                                        this.aB = new jb();
                                        this.bR = new j9();
                                        this.bT = new jz();
                                        this.o = new jH();
                                        this.a4 = new jf();
                                        this.aT = new j1();
                                        this.ad = new jU();
                                        this.bH = new ju();
                                        this.ao = new jQ();
                                        this.co = new ko();
                                        this.ap = new jo();
                                        this.b8 = new j3();
                                        this.cj = new ik();
                                        this.i = new hJ();
                                        this.aV = new im();
                                        this.be = new jp();
                                        this.m = new jW();
                                        this.cc = new jV();
                                        this.ce = new jX();
                                        this.bx = new ic();
                                        this.aI = new i5();
                                        this.j = new iu();
                                        this.bO = new iE();
                                        this.b2 = new ig();
                                        this.bf = new il();
                                        this.ck = new jq();
                                        this.aN = new jE();
                                        this.bt = new gL();
                                        this.cw = new gr();
                                        this.L = new je();
                                        this.ag = new iI();
                                        this.a5 = new jd();
                                        this.v = new jc();
                                        this.bk = new ij();
                                        this.C = new iy();
                                        this.bU = new in();
                                        this.cy = new iN();
                                        this.bE = new iZ();
                                        this.W = new jM();
                                        this.H = new jg();
                                        this.ay = new jt();
                                        this.N = new jZ();
                                        this.a2 = new ia();
                                        this.a3 = new jL();
                                        this.aE = new iL();
                                        this.aG = new iM();
                                        this.T = new jn();
                                        this.b4 = new jI();
                                        this.S = new jF();
                                        this.cz = new jJ();
                                        this.r = new jr();
                                        this.az = new j2();
                                        this.bF = new k3();
                                        this.bo = new kQ();
                                        this.bQ = new h_();
                                        this.aC = new hs();
                                        this.ah = new hB();
                                        this.Q = new ih();
                                        this.bD = new iW();
                                        this.a9 = new jY();
                                        this.w = new jv();
                                        this.aS = new iJ();
                                        this.aH = new i2();
                                        this.ci = new jx();
                                        this.bn = new jA();
                                        this.cm = new jO();
                                        this.ai = new ja();
                                        this.bw = new js();
                                        this.G = new ib();
                                        this.aO = new i4();
                                        this.cn = new iv();
                                        this.b1 = new iY();
                                        this.aW = new iP();
                                        this.ab = new iF();
                                        this.aR = new iR();
                                        this.ba = new hd();
                                        this.bX = new i0();
                                        this.k = new iO();
                                        this.aZ = new hX();
                                        this.b6 = new iS();
                                        this.aD = new iK();
                                        this.p = new iH();
                                        this.bL = new hZ();
                                        this.f = new j5();
                                    }
                                    if (n6 == 0) break block14;
                                    if (A5.dR == null) break block15;
                                    this.J = new kk();
                                }
                                on.D = true;
                            }
                            if (manthe.V.c() <= 13) break block16;
                            this.a8 = new iQ();
                            this.cf = new i3();
                            this.by = new hT();
                            this.cp = new jS();
                            this.bc = new hj();
                            this.ac = new j_();
                            this.V = new kg();
                            this.bN = new jC();
                            this.bY = new hU();
                            this.b7 = new hP();
                            this.as = new jl();
                            this.ae = new hF();
                            this.ak = new i7();
                            this.F = new i9();
                            this.bs = new iG();
                            this.a6 = new kM();
                            this.cx = new hR();
                            this.D = new jB();
                            this.ai = new ja();
                            this.E = new h0();
                            this.D = new jB();
                            this.bl = new jm();
                            this.aj = new ha();
                            this.l = new hN();
                            this.ar = new hp();
                            this.al = new hv();
                            this.t = new hY();
                            if (n6 != 0) break block17;
                        }
                        this.y = new hD();
                        this.aw = new hq();
                    }
                    if (manthe.V.c() < 23) break block18;
                    this.bi = new iU();
                    this.bu = new jR();
                    this.bJ = new i8();
                    this.cd = new iB();
                    this.bv = new j8();
                    this.af = new j6();
                    this.a7 = new hi();
                    if (n6 != 0) break block19;
                }
                this.bm = new hy();
            }
            if (A5.bA != null) {
                this.A = new hf();
                this.cb = new hK();
                this.b3 = new h1();
            }
            this.cg = new hH();
            if (manthe.cy.c()) break block20;
            gJ.b(++n6);
        }
    }

    static {
        manthe.t.b(new String[4]);
    }

    public static void b(String[] arrstring) {
        aK = arrstring;
    }

    public static String[] b() {
        return aK;
    }

    private static CodeAttribute$RuntimeCopyException a(CodeAttribute$RuntimeCopyException codeAttribute$RuntimeCopyException) {
        return codeAttribute$RuntimeCopyException;
    }
}

